options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
          - docker build -t rossedlin/php-apache:7.1 .
          - docker push rossedlin/php-apache:7.1
        services:
          - docker
