name: Build

on:
  push:
    branches: [ "v8.1" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker Image
        run: docker build -t rossedlin/php-apache:8.1 .

      - uses: actions/checkout@v4
      - name: Login to Docker
        run: echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ vars.DOCKER_HUB_USER }} --password-stdin

      - uses: actions/checkout@v4
      - name: Push Image to Docker
        run: docker push rossedlin/php-apache:8.1
