name: Docker Image CI

on:
  push:
    branches: [ "v8.3" ]
  pull_request:
    branches: [ "v8.3" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t rossedlin/php-apache:8.3 .
